### PR TITLE
change locations

### PR DESCRIPTION
**Pull request by katsuyoshi**
Hello sylverb.
Thank you for adopting my patches.

I have another patch.
To import CIALBrowser I had to do few steps to add files into Xcode project.
By this patch, just drag the CIALBrowser folder to a Xcode project.

If you like this construction, please merge this patch.

### CODE REVIEW

**Comment by sylverb** [comment]
Thanks for this also.
But you did add some useless files in the git repository (like CIALBrowserViewControllerDemo.xcodeproj/xcuserdata/ISD.xcuserdatad/xcschemes/xcschememanagement.plist for example). The only file in the CIALBrowserViewControllerDemo.xcodeproj folder that should be part of the repository is CIALBrowserViewControllerDemo.xcodeproj/project.pbxproj . Please send a modified pull request to remove these useless files (I'll add a .gitignore file after that to prevent these file to be part of the repository).

**Comment by katsuyoshi** [comment]
I'm sorry.
I removed useless files and fixed gitignore file.

**Comment by sylverb** [comment]
Thanks Katsuyoshi !
When I'll have some time I'll move all the the graphical ressources in a bundle to make integration even easier !

**Comment by katsuyoshi** [comment]
Thank you too sylverb.

I want to add a Japanese Localization file if I have a time.
Then it become a perfect for me.
I'll send pull request again,  when I had implemented it.

Regards Katsuyoshi.

**Pull request merged**
